### ISSUE TITLE
#Bug 1 root授权失败时的行为

### ISSUE THREAD

**Issue by FindHao** [FindHao/CoolHosts#1]
+ 如果正常授权失败，按钮动画会一直转圈
+ 如果授权了但是锁了system分区，无法创建rootcheck文件，则会崩溃。
```
 java.io.FileNotFoundException: /system/rootcheck.txt: open failed: ENOENT (No such file or directory)
	RootChecker	         at libcore.io.IoBridge.open(IoBridge.java:460)
	RootChecker	         at java.io.FileInputStream.(FileInputStream.java:78)
	RootChecker	         at java.io.FileInputStream.(FileInputStream.java:105)
	RootChecker	         at java.io.FileReader.(FileReader.java:66)
	RootChecker	         at com.find.coolhosts.RootChecker.readFileContents(RootChecker.java:66)
	RootChecker	         at com.find.coolhosts.RootChecker.hasRoot(RootChecker.java:32)
	RootChecker	         at com.find.coolhosts.CoolHosts.onResume(CoolHosts.java:101)
```

**Comment by FindHao** [comment]
v2.1.7 修复了此bug。解决方法是采用了RootTool这个包来验证root与否。
